spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://127.0.0.1:5432/demon
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true


